ARG NODE_VERSION=22
ARG PORT=3000

FROM node:${NODE_VERSION}-alpine

WORKDIR /app

# Copy package files
COPY package*.json ./
RUN npm install

# Copy source code
COPY . .

# Expose port
EXPOSE ${PORT}

# Start development server
CMD sleep 20 && npm run dev