# Working directory
root = "."
tmp_dir = "tmp"

[build]
# shell command
cmd = "go build -o ./tmp/main ."
# Add additional arguments when running binary (bin/full_bin).
args_bin = []
# Binary file yields from `cmd`.
bin = "tmp/main"
# Customize binary, can setup environment variables when run your app.
full_bin = "./tmp/main"

# It's not necessary to trigger build each time file changes if it's too frequent.
delay = 1000 # ms
# Ignore these filename extensions or directories.
exclude_dir = ["assets", "tmp", "vendor"]
# Exclude files.
exclude_file = []
# Exclude specific regular expressions.
exclude_regex = ["_test\\.go$", ".*\\.test\\.go$"]
# Exclude unchanged files.
exclude_unchanged = true
# Follow symlink for directories
follow_symlink = false

# Watch these directories if you specified.
include_dir = []
# Watch these filename extensions.
include_ext = ["go", "tpl", "tmpl", "html", "mod", "sum", "env"]
# Watch these files.
include_file = [".env", "go.mod", "go.sum"]

# Delay after sending Interrupt signal
kill_delay = "2s"
# This log file is placed in your tmp_dir.
log = "air-errors.log"
# Poll files for changes instead of using fsnotify.
poll = true
# Poll interval (defaults to the minimum interval of 500ms).
poll_interval = 500
# Rerun binary or not
rerun = false
# Delay after each execution
rerun_delay = 500
# Send Interrupt signal before killing process (windows does not support this feature)
send_interrupt = true
# Stop on build errors
stop_on_error = true
# Stop running old binary when build errors occur.
stop_on_root = true

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
# Only show main log (silences watcher, build, runner)
main_only = false
# Show log time
time = true

[misc]
# Delete tmp directory on exit
clean_on_exit = true

[screen]
clear_on_rebuild = true
keep_scroll = true