# Build arguments
ARG GO_VERSION=1.24
ARG PORT=8000

# Base stage
FROM golang:${GO_VERSION}-alpine AS base

# Install system dependencies
RUN apk update && apk add --no-cache \
    git \
    bash \
    curl \
    ca-certificates \
    && rm -rf /var/cache/apk/*

# Install air for hot reloading
RUN go install github.com/air-verse/air@v1.52.3

WORKDIR /app

# Copy dependency files
COPY go.mod go.sum ./
RUN go mod download && go mod verify

# Copy source code
COPY . .

# Expose port
EXPOSE ${PORT}

# Start run air
CMD ["air", "-c", ".air.toml"]