/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/{product}/resources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List resources */
        get: operations["listResources"];
        put?: never;
        /** Create resource */
        post: operations["createResource"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/{product}/resources/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get resource by ID */
        get: operations["getResourceById"];
        put?: never;
        post?: never;
        /** Delete resource */
        delete: operations["deleteResource"];
        options?: never;
        head?: never;
        /** Update resource */
        patch: operations["updateResource"];
        trace?: never;
    };
    "/api/v1/{product}/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get tags */
        get: operations["listTags"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        ResourceType: "video" | "pdf" | "article";
        Resource: {
            id: string;
            title: string;
            description: string;
            type: components["schemas"]["ResourceType"];
            /** Format: uri */
            url: string;
            /** Format: uri */
            thumbnailUrl?: string;
            tags: string[];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        Tag: {
            name: string;
            usageCount: number;
        };
        PaginatedResourceResponse: {
            data: components["schemas"]["Resource"][];
            hasMore: boolean;
            nextCursor?: string;
        };
        CreateResourceRequest: {
            title: string;
            description: string;
            type: components["schemas"]["ResourceType"];
            /** @description Comma-separated tags */
            tags: string;
            /** Format: uri */
            url?: string;
            /** Format: uri */
            thumbnailUrl?: string;
            /** Format: binary */
            file?: string;
            /** Format: binary */
            thumbnail?: string;
        };
        UpdateResourceRequest: {
            title?: string;
            description?: string;
            type?: components["schemas"]["ResourceType"];
            /** @description Comma-separated tags */
            tags?: string;
            /** Format: uri */
            url?: string;
            /** Format: uri */
            thumbnailUrl?: string;
            /** Format: binary */
            file?: string;
            /** Format: binary */
            thumbnail?: string;
        };
        DeleteResourceResponse: {
            message: string;
        };
        ErrorResponse: {
            error: string;
            message?: string;
            details?: string;
        };
    };
    responses: {
        /** @description Error response */
        ErrorResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /** @description Product scope identifier */
        ProductPathParam: string;
        /** @description Resource identifier */
        ResourceIdPathParam: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listResources: {
        parameters: {
            query?: {
                type?: "video" | "pdf" | "article" | "all";
                /** @description Comma-separated tags */
                tags?: string;
                search?: string;
                /** @description Offset encoded as string */
                cursor?: string;
                /** @description Items per page */
                limit?: string;
            };
            header?: never;
            path: {
                /** @description Product scope identifier */
                product: components["parameters"]["ProductPathParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resources list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResourceResponse"];
                };
            };
            400: components["responses"]["ErrorResponse"];
            500: components["responses"]["ErrorResponse"];
        };
    };
    createResource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Product scope identifier */
                product: components["parameters"]["ProductPathParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["CreateResourceRequest"];
            };
        };
        responses: {
            /** @description Resource created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resource"];
                };
            };
            400: components["responses"]["ErrorResponse"];
            404: components["responses"]["ErrorResponse"];
            500: components["responses"]["ErrorResponse"];
        };
    };
    getResourceById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Product scope identifier */
                product: components["parameters"]["ProductPathParam"];
                /** @description Resource identifier */
                id: components["parameters"]["ResourceIdPathParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resource details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resource"];
                };
            };
            400: components["responses"]["ErrorResponse"];
            404: components["responses"]["ErrorResponse"];
            500: components["responses"]["ErrorResponse"];
        };
    };
    deleteResource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Product scope identifier */
                product: components["parameters"]["ProductPathParam"];
                /** @description Resource identifier */
                id: components["parameters"]["ResourceIdPathParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resource deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteResourceResponse"];
                };
            };
            400: components["responses"]["ErrorResponse"];
            404: components["responses"]["ErrorResponse"];
            500: components["responses"]["ErrorResponse"];
        };
    };
    updateResource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Product scope identifier */
                product: components["parameters"]["ProductPathParam"];
                /** @description Resource identifier */
                id: components["parameters"]["ResourceIdPathParam"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["UpdateResourceRequest"];
            };
        };
        responses: {
            /** @description Resource updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resource"];
                };
            };
            400: components["responses"]["ErrorResponse"];
            404: components["responses"]["ErrorResponse"];
            500: components["responses"]["ErrorResponse"];
        };
    };
    listTags: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Product scope identifier */
                product: components["parameters"]["ProductPathParam"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tags list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tag"][];
                };
            };
            400: components["responses"]["ErrorResponse"];
            500: components["responses"]["ErrorResponse"];
        };
    };
}
